### ISSUE TITLE
Add 1 level sub-directory representation to the docs side-nav

### ISSUE THREAD

**Issue by zoharbabin** [kaltura/DeveloperPortalDocs#7]
Please see attached screenshot:
![side-menu-sub-directories](https://cloud.githubusercontent.com/assets/150514/14635657/10bf38ca-0630-11e6-9148-8c7db5ea4c65.png)

**Comment by jessp01** [comment]
Done. In order to attach a doc to a sub category, add:
subcat: CatName
to the front matter. See example here:
https://github.com/kaltura/DeveloperPortalDocs/blob/master/documentation/player-sdk/Android-API-Events-And-Hooks.md

The CSS classes are here:
https://github.com/kaltura/DeveloperPortalDocs/blob/master/css/kaltura-dev-site.webflow.css#L689
https://github.com/kaltura/DeveloperPortalDocs/blob/master/css/kaltura-dev-site.webflow.css#L727

Go ahead and edit them to your liking.
